# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15
ARG UPSTREAM_URL="https://api.github.com/repos/immich-app/immich/releases/latest"

# Pull Linux image for pre-built corePlugin WASM (extism-js has no FreeBSD release)
FROM --platform=linux/amd64 ghcr.io/immich-app/immich-server:release AS linux-immich

FROM ghcr.io/daemonless/base:${BASE_VERSION} AS builder

ARG UPSTREAM_URL

# Build dependencies (including C++ compiler and headers for native modules)
# FreeBSD base dev packages needed for pkg-config: openssl, zlib, xz (lzma), bzip2
RUN pkg update && pkg install -y \
    jq \
    node22 npm-node22 \
    git-lite gmake pkgconf \
    FreeBSD-clang FreeBSD-clibs-dev \
    FreeBSD-openssl-dev FreeBSD-zlib-dev FreeBSD-xz-dev FreeBSD-bzip2-dev \
    python311 \
    vips \
    ffmpeg \
    p5-Image-ExifTool \
    libheif \
    libraw \
    webp \
    && pkg clean -ay

# Set up compiler symlinks for node-gyp
RUN ln -sf /usr/bin/clang++ /usr/bin/c++ && \
    ln -sf /usr/bin/clang /usr/bin/cc

# Enable corepack for pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Clone immich source (resolve latest version from upstream)
WORKDIR /build
RUN --mount=type=secret,id=github_token \
    FETCH_URL="${UPSTREAM_URL}"; \
    GITHUB_TOKEN=$(cat /run/secrets/github_token 2>/dev/null || echo ""); \
    if [ -n "${GITHUB_TOKEN}" ]; then \
      FETCH_URL=$(echo "${UPSTREAM_URL}" | sed "s|https://|https://x-access-token:${GITHUB_TOKEN}@|"); \
    fi && \
    IMMICH_VERSION=$(fetch -qo - "${FETCH_URL}" | jq -r '.tag_name') && \
    echo "Resolved IMMICH_VERSION=$IMMICH_VERSION" && \
    git clone --depth 1 --branch ${IMMICH_VERSION} \
      https://github.com/immich-app/immich.git . && \
    echo "${IMMICH_VERSION}" > /tmp/immich_version

# Build server
WORKDIR /build/server

# Patch sharp to recognize UHDR loader (libvips 8.18+)
RUN pnpm install --frozen-lockfile && \
    SHARP_DIR=$(find /build/node_modules/.pnpm -name 'sharp' -type d -path '*/node_modules/sharp' | head -1) && \
    sed -i '' 's/VIPS,/VIPS, UHDR,/' "$SHARP_DIR/src/common.h" && \
    sed -i '' 's/{ "VipsForeignLoadJpegFile"/{ "VipsForeignLoadUhdrFile", ImageType::UHDR },\n    { "VipsForeignLoadUhdrBuffer", ImageType::UHDR },\n    { "VipsForeignLoadJpegFile"/' "$SHARP_DIR/src/common.cc" && \
    cd "$SHARP_DIR/src" && PYTHON=/usr/local/bin/python3.11 node-gyp rebuild

RUN pnpm build

# Deploy production dependencies only
RUN pnpm deploy --filter immich --prod /app && \
    SHARP_BUILD=$(find /build/node_modules/.pnpm -name 'sharp-freebsd-x64.node' -path '*/src/build/Release/*' | head -1) && \
    SHARP_DEST=$(find /app/node_modules/.pnpm -name 'sharp' -type d -path '*/node_modules/sharp' | head -1) && \
    mkdir -p "$SHARP_DEST/src/build/Release" && \
    cp "$SHARP_BUILD" "$SHARP_DEST/src/build/Release/"

# Build web UI (increase heap for vite build)
WORKDIR /build
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN pnpm --filter @immich/sdk --filter immich-web install --frozen-lockfile
RUN pnpm --filter @immich/sdk --filter immich-web build
RUN mkdir -p /app/www && cp -r /build/web/build/* /app/www/

# Copy pre-built corePlugin from Linux image (extism-js doesn't have FreeBSD releases)
# The WASM plugin is platform-independent, so we can use the Linux build
COPY --from=linux-immich /build/corePlugin /app/corePlugin

# Download geodata for reverse geocoding
RUN mkdir -p /app/geodata && \
    fetch -o /app/geodata/admin1CodesASCII.txt https://download.geonames.org/export/dump/admin1CodesASCII.txt && \
    fetch -o /app/geodata/admin2Codes.txt https://download.geonames.org/export/dump/admin2Codes.txt && \
    fetch -o /app/geodata/cities500.zip https://download.geonames.org/export/dump/cities500.zip && \
    unzip -o /app/geodata/cities500.zip -d /app/geodata && \
    rm /app/geodata/cities500.zip && \
    fetch -o /app/geodata/ne_10m_admin_0_countries.geojson "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_0_countries.geojson" && \
    date +%Y-%m-%d > /app/geodata/geodata-date.txt

# Production image
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="node22 vips ffmpeg p5-Image-ExifTool libheif libraw webp"
ARG UPSTREAM_URL="https://api.github.com/repos/immich-app/immich/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:2283/api/server-info/ping"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Immich Server" \
      org.opencontainers.image.description="Immich photo management server on FreeBSD." \
      org.opencontainers.image.source="https://github.com/daemonless/immich-server" \
      org.opencontainers.image.url="https://immich.app/" \
      org.opencontainers.image.version="latest" \
      org.opencontainers.image.licenses="AGPL-3.0" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Photos & Media" \
      io.daemonless.port="2283" \
      io.daemonless.volumes="/config,/data" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

# Install runtime dependencies
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    mkdir -p /app && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/* && \
    rm -rf /usr/local/libexec/gcc14 /usr/local/bin/lto-dump14 && \
    rm -f /usr/local/lib/libopcodes* /usr/local/lib/libbfd*

# Copy version and built application from builder
COPY --from=builder /tmp/immich_version /tmp/immich_version
COPY --from=builder --chown=bsd:bsd /app /app

# Create directories, write version, and symlinks (paths match Linux immich expectations)
RUN cp /tmp/immich_version /app/version && \
    mkdir -p /config /data /build && \
    mkdir -p /data/{encoded-video,thumbs,upload,profile,backups,library} && \
    chown -R bsd:bsd /config /data /build && \
    ln -sf /app/www /build/www && \
    ln -sf /app/corePlugin /build/corePlugin && \
    ln -sf /app/geodata /build/geodata && \
    chown -h bsd:bsd /build/www /build/corePlugin /build/geodata && \
    chmod 755 /app/geodata && chmod 644 /app/geodata/*

# Copy service files
COPY root/ /
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* 2>/dev/null || true

WORKDIR /app

ENV NODE_ENV=production
ENV IMMICH_PORT=2283
ENV IMMICH_MEDIA_LOCATION=/data

# --- Expose (Injected by Generator) ---
EXPOSE 2283

# --- Volumes (Injected by Generator) ---
VOLUME /config /data