icon: ':material-server:'
# Only test shell, we need depends, which will be tested in daemonless/immich
cit:
  mode: shell

build:
  variants:
    # NOTE: We'll link beta to latest until Immich offers a newer beta.
    - tag: latest
      containerfile: Containerfile
      default: true
      aliases: [beta]
